function[f] = extract_frequency(filename, startRow, endRow)
%% Import data from text file.
% Function for importing data from '*.ddf' files
%
% Auto-generated by MATLAB on 2018/02/10 13:27:24

%% Initialize variables.
delimiter = {'\t',','};
startRow = 15;
endRow = 15;

%% Format for each line of text:
%   column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray2 = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
f = dataArray2{:, 1};


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray2 ans;